"""@generated by @rules_ruby//:ruby/private/bundle_fetch.bzl"""

load("@rules_ruby//ruby:defs.bzl", "rb_bundle_gem_install", "rb_bundle_install", "rb_library")

package(default_visibility = ["//visibility:public"])

# rb_library(
#     name = "{name}",
#     data = glob(["bin/*"]),
#     deps = [":{name}_install"],
# )

rb_bundle_install(
    name = "{name}",
    srcs = {srcs},
    gemfile = "Gemfile",
    gemfile_lock = "Gemfile.lock",
    gems = {gems},
)

[
    rb_bundle_gem_install(
        name = gem[:-4],
        gem = gem,
    )
    for gem in glob(["*.gem"])
]

# vim: ft=bzl
